In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from IPython.display import display
import pandas as pd
import h5py
import os
# to load data from the test file
from utils.create_datasets import SumDatasets
# To load the data sets here, also we will create some examples to explore torch
data_dir = '../data/'
from utils import config
import pickle

/home/chenxiang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sum_dataset = SumDatasets(os.path.join(data_dir, 'features-600-40_v2.hdf5'))

The shape of the features_1 is (145821, 600)
The shape of the features_2 is (145821,)
The shape of the features_3 is (145821, 40)


In [3]:
features_1, features_2, features_3, features_4 = sum_dataset[1:10] # assume we have a batch data of 20 items.
display(features_2)
display(features_1)

AttributeError: 'numpy.ndarray' object has no attribute 'squeeze_'

In [9]:

batch_size = features_1.size(0)
if batch_size == 1:
    pass
else:
    sorted_length, sorted_idx = features_2.sort()  # sort will return both the ascending sorted value and also the sorted i    ndex
    reverse_idx = torch.linspace(batch_size - 1, 0, batch_size).long()  # this will contain the batch_size-1
    sorted_length, sorted_idx = sorted_length[reverse_idx], sorted_idx[reverse_idx]
    features_1 = features_1[sorted_idx]
    features_2 = features_2[sorted_idx]
    features_3 = features_3[sorted_idx]
    features_4 = features_4[sorted_idx]


In [19]:
display(features_2)
sorted_length, sorted_idx = features_2.sort()
reverse_idx = torch.linspace(batch_size - 1, 0, batch_size).long()
sorted_length, sorted_idx = sorted_length[reverse_idx], sorted_idx[reverse_idx]
display(sorted_length)

tensor([600, 600, 600, 600, 600, 600, 600, 436, 600])

tensor([600, 600, 600, 600, 600, 600, 600, 600, 436])

In [15]:
original_data = pd.read_csv(os.path.join(data_dir, 'test_data.csv'), encoding='utf-8')
original_data['content_len'] = original_data.content.apply(lambda x: len(x.split()))
display(original_data.head(n=20))

id                                            content  \
0    1  This was the year that felt like 50 years. We ...   
1    2  Gary Vaynerchuk once told a 20 year old Taylor...   
2    3  On this episode of Recode Decode, hosted by Ka...   
3    4  Today we are going to talk about the Albigensi...   
4    5  IntroductionThe more you want to impact the re...   
5    6  I began my short term (sometimes business rela...   
6    7  Either I’ve become way better at choosing whic...   
7    8  You can feel it: 2018 is the year you finally ...   
8    9  U.S. Soccer Federation president Sunil Gulati ...   
9   10  When things get tough or simply flat, many peo...   
10  11  Germany, Sweden, Denmark, Norway, Finland are ...   
11  12  I have been fortunate enough to learn so much ...   
12  13  The most comprehensive list on the internet. Y...   
13  14  For the last year or so, I’ve been struggling ...   
14  15  Of Bonaventure, Black Holes and Whitehead (Par...   
15  16  We want to know the magic formula, the potion ...   
16  17  (Credit: Getty/AP/Salon)Is he the goofball acc...   
17  18  In the past months, I’d launched a number of w...   
18  19  Business Model Generation (Alexander Osterwald...   
19  20  Cuba's Brad Pitt asks me to dance.    This is ...   

                                                title  content_len  
0                21 Stories Our Readers Loved in 2017         4142  
1                 What To Do After Graduating College         2054  
2   Full transcript: Former Groupon CEO Andrew Mas...        11679  
3          The Albigensian Crusade And The Black Mass          992  
4         The Surprising Secret To Changing The World         5153  
5   Five Things I’ve Learned from Short-Term Trave...          866  
6        Influential books I read in the last 2 years         2993  
7   How to spend less, save more, and clean up you...         1617  
8              Face of US Soccer since 2006 wants out          421  
9   Leaving Google for Friendz: how we did handle ...         1277  
10  India: How to deliver free high quality engine...         1548  
11   10 Life Lessons I Have Learned Before Turning 18         1461  
12                     The A-Z Glossary for Marketers         5973  
13                    The Light that Casts the Shadow         2030  
14          Of Bonaventure, Black Holes and Whitehead          916  
15    Jimmy Garoppolo Begins Bright Future With 49ers         2083  
16  One year, many Trumps: 2017’s 10 best theories...         3356  
17             Ask Me Anything: Team Development pt 2         1227  
18  Business Model Generation (Alexander Osterwald...         1828  
19                                   Cuba's Wild Side         1772

In [20]:
from utils.create_datasets import Entry
with open(os.path.join(data_dir, 'Vocab.pkl'), 'rb') as f:
    Vocab_ = pickle.load(f)

In [21]:
example_content, example_title = original_data.content[8], original_data.title[8]
an_example = Entry(example_content, example_title, vocab=Vocab_)

In [23]:
an_example.pad_encoder_input(config.max_enc_steps,0)
an_example.pad_decoder_inp_targ(config.max_dec_steps, 0)
an_example.enc_len

421

In [7]:
embedding_dim = 50
hidden_dim = 10
# for the padding index 0 and the Unktoken vocab_size + 1, so there will be NUM_WORDS+2
# tokens
embedding = nn.Embedding(config.NUM_WORDS +2, embedding_dim=embedding_dim)
lstm = nn.LSTM(embedding_dim, hidden_dim)

In [8]:
x = torch.from_numpy(example_1[0])

In [18]:
embeded_x = embedding(x)
output, hidden = lstm(embeded_x)
h = output.contiguous()
display(h.shape)
max_h, _ = h.max(dim=1) # find each batch's maximum hidden state
display(max_h)

torch.Size([20, 600, 10])

tensor([[0.5158, 0.5986, 0.5767, 0.6330, 0.6154, 0.5766, 0.5469, 0.5183, 0.5927,
         0.6202],
        [0.7223, 0.7004, 0.7794, 0.7969, 0.6252, 0.6994, 0.6700, 0.5775, 0.7517,
         0.5574],
        [0.7473, 0.7252, 0.7682, 0.7023, 0.5624, 0.8189, 0.6409, 0.5131, 0.7309,
         0.4857],
        [0.5584, 0.6599, 0.6808, 0.7636, 0.5259, 0.7098, 0.5762, 0.4847, 0.6862,
         0.6399],
        [0.6476, 0.7076, 0.5770, 0.7636, 0.6496, 0.6973, 0.7276, 0.4431, 0.7674,
         0.7345],
        [0.6452, 0.7501, 0.7968, 0.8239, 0.5946, 0.7437, 0.7452, 0.5760, 0.7495,
         0.7888],
        [0.6735, 0.7684, 0.7626, 0.8101, 0.5257, 0.6962, 0.7921, 0.6199, 0.6625,
         0.6860],
        [0.6611, 0.7546, 0.9221, 0.8342, 0.5152, 0.5993, 0.5278, 0.5426, 0.7551,
         0.7246],
        [0.6412, 0.7144, 0.7900, 0.6860, 0.5302, 0.7327, 0.5842, 0.4725, 0.6623,
         0.7129],
        [0.6147, 0.6282, 0.7176, 0.7142, 0.7873, 0.7952, 0.7722, 0.4929, 0.7931,
         0.7722],
        [0

In [13]:
h_c, h_ = hidden

In [19]:
h_c.unsqueeze(0).shape

torch.Size([1, 1, 600, 10])